services:

  app:
    build:
      context: chainlit_app/
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - MODEL_URL=http://model-mistral
      - DB_URL=http://db-chroma
      - MODEL_PORT=8007
      - DB_PORT=8006
    volumes:
      - rag-volume:/chainlit_app/database

  model-mistral:
    image: llm-model
    build:
      context: llm_models/mistral
      dockerfile: Dockerfile
    ports:
      - 8007:8007
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  db-chroma:
    image: chroma
    build:
      context: vectordbs/Chroma
      dockerfile: Dockerfile
    ports:
      - 8006:8006

networks:
  default:
    name: milvus

volumes:
  rag-volume:
    driver: local
