services:
  server:
    image: aimstack/aim:3.24.0
    command: server --host 0.0.0.0
    container_name: aim_server
    ports:
        - 53800:53800 
    volumes:
        - aim-volume:/opt/aim

  ui:
    image: aimstack/aim:3.24.0
    command: up --host 0.0.0.0
    container_name: aim_ui
    ports:
        - 43800:43800
    volumes:
        - aim-volume:/opt/aim

networks:
  default:
    name: lines-network

volumes:
  aim-volume:
    driver: local

