services:

  app:
    build:
      context: chainlit_app/
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    env_file:
      - chainlit_app/.env
    environment:
      - MODEL_URL=${MODEL_URL:-http://ollama}
      - MODEL_PORT=${MODEL_PORT:-11434}
      - DB_URL=http://db-chroma
      - DB_PORT=8006
    volumes:
      - rag-volume:/chainlit_app/database

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    environment:
      - OLLAMA_DEBUG=true
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    # command: "ollama run llama3.1"

  db-chroma:
    image: chroma
    build:
      context: vectordbs/Chroma
      dockerfile: Dockerfile
    ports:
      - 8006:8006

networks:
  default:
    name: milvus

volumes:
  ollama:
    name: ollama
  rag-volume:
    driver: local

