services:

  ollama:
    container_name: ollama
    image: ollama/ollama:0.6.0
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_DEBUG=true
      - CUDA_VISIBLE_DEVICES=0
    entrypoint: bash -c "ollama serve & pid=$!; sleep 5; ollama pull llama3.1; ollama pull gemma2:2b; ollama pull granite-embedding:278m; wait $pid"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  
  aim-server:
    image: aimstack/aim:3.24.0
    command: server --host 0.0.0.0
    container_name: aim_server
    ports:
        - 53800:53800 
    volumes:
        - aim-volume:/opt/aim

  aim-ui:
    image: aimstack/aim:3.24.0
    command: up --host 0.0.0.0
    container_name: aim_ui
    ports:
        - 43800:43800
    volumes:
        - aim-volume:/opt/aim

networks:
  default:
    name: lines-network

volumes:
  ollama:
    name: ollama
  rag-volume:
    driver: local
  transformer-volume:
    driver: local
  aim-volume:
    driver: local
