services:

  app:
    build:
      context: chainlit_app/
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - MODEL_URL=http://model-reyna
      - DB_URL=http://db-chroma
      - MODEL_PORT=8007
      - DB_PORT=8006
    volumes:
      - rag-volume:/chainlit_app/database


  model-reyna:
    image: reyna
    build:
      context: llm_models/reyna_cpu
      dockerfile: Dockerfile
    ports:
      - 8007:8007

  db-chroma:
    image: chorma
    build:
      context: vectordbs/Chroma
      dockerfile: Dockerfile
    ports:
      - 8006:8006

networks:
  default:
    name: milvus

volumes:
  rag-volume:
    driver: local
