version: '3.8'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - rag-volume:/app/database
    networks:
      - lines-network

  llm-model:
    image: llm-model
    build:
      context: gguf_model
      dockerfile: Dockerfile
    ports:
      - 8007:8007
    networks:
      - lines-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]


networks:
  lines-network:
    driver: bridge

volumes:
  rag-volume:
    driver: local
