FROM python

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir huggingface-hub

WORKDIR /app

RUN huggingface-cli download aloobun/Reyna-Mini-1.8B-v0.2 --local-dir . --local-dir-use-symlinks False

COPY requirements.txt /app
RUN pip install --no-cache-dir -r requirements.txt

COPY main.py /app

CMD ["python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8007", "--reload"]
